config/routes.rb
Ideya::Application.routes.draw do

  root 'title#index'
  
  devise_for :users, format: false
 
  resources :papers , except: [:show,:destroy],  format: false
  #get 'papers/:id/delete'   => 'papers#destroy',    as: :delete_paper, format: false
  get 'papers/page/:page'   => 'papers#index' ,     as: :paper_page,    format: false
  get 'papers/:id'          => 'papers#show'  ,                         format: false, constraints: { id: /\d*/ }
  get 'papers/:urlname'     => 'papers#byname',     as: :paper_byname,  format: false
  get 'paper_main'          => 'papers#main'  ,     as: :paper_main,    format:false
   
  resources :news , controller: :novosts, as: :novosts, format: false  , except: [:show,:destroy]
  get 'news/admin'          => 'novosts#index_adm', as: :novosts_adm,   format: false
  get 'news/:id/delete'     => 'novosts#destroy'  , as: :delete_novost, format: false
  get 'news/:id'            => 'novosts#show'     ,                     format: false, constraints: { id: /\d*/ }
  get 'news/page/:page'     => 'novosts#index'    , as: :novosts_page,  format: false
  
  resources :articles, except: [:show,:destroy],  format: false
  get 'articles/admin'      => 'articles#index_adm',as: :articles_adm,  format: false
  get 'articles/:id/delete' => 'articles#destroy' , as: :delete_article,format: false
  get 'articles/page/:page' => 'articles#index' ,   as: :articles_page, format: false
  get 'articles/:id'        => 'articles#show'  ,                       format: false, constraints: { id: /\d*/ }

  resources :partners, format: false  , except: [:show,:destroy]
  get 'partners/:id'        => 'partners#show',                         format: false, constraints: { id: /\d*/ }
  get 'partners/:id/delete' => 'partners#destroy',  as: :delete_partner,format: false

  resources :siteimages, format: false, except: [:destroy]
   get 'siteimages/:id/delete'   => 'siteimages#destroy'    , as: :delete_siteimage,  format: false
    
  resources :issues , controller: :issues, as: :issues, format: false  , except: [:show,:destroy,:update], shallow: true do
    resources :issuepages , controller: :issuepages, path: :papers,  format: false, except: [:show,:destroy,:update,:edit]  
  end
  get 'issues/:id'            => 'issues#show'        , as: :issue,            format: false, constraints: { id: /\d*/ }
  get 'issues/page/:page'     => 'issues#index'       , as: :issues_page,      format: false
  get 'issues/:id/delete'     => 'issues#destroy'     , as: :delete_issue,     format: false
  get 'issues/admin'          => 'issues#index_adm'   , as: :issues_adm,       format: false
  get 'issuepages/:id/delete' => 'issuepages#destroy' , as: :delete_issuepage, format: false
  get 'issues/:issue_id/page/:page' => 'issuepages#index'  , as: :issuepages_page,      format: false
  get 'issues/:issue_id/cover/:id' => 'issuepages#cover'  , as: :cover_issuepage,      format: false


  get  'feedback/ads'   => 'feedback#ads'        , as: :feedback_ads        , format: false
  post 'feedback/ads'   => 'feedback#ads_post'   , as: :post_feedback_ads   , format: false
  get  'feedback/ideya' => 'feedback#ideya'      , as: :feedback_ideya      , format: false
  post 'feedback/ideya' => 'feedback#ideya_post' , as: :post_feedback_ideya , format: false

  get  'feedback/akciya1' => 'feedback#akciya1'      , as: :feedback_akciya1      , format: false
  post 'feedback/akciya1' => 'feedback#akciya1_post' , as: :post_feedback_akciya1 , format: false

  get  'vk/albums' => 'vkphotos#index' , as: :vkalbums , format: false
  get  'vk/photos/:id' => 'vkphotos#photos'  , format: false


#  get  'search/*arg' => 'search#index', as: :search ,format: false #

  get 'template/*arg' => 'template#index', as: :template, format: false

  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
    get '422', :to => 'application#server_error'
    get '500', :to => 'application#server_error'
  end

#  get 'otzivi'   => 'staticviews#ozivs'    , as: :otzivs_page, format: false

end

app/models/issue.rb
# encoding: utf-8
class Issue < ActiveRecord::Base
  belongs_to :cover ,class_name: "Issuepage"
  has_many :issuepages, :dependent => :destroy
  validates :caption, length: { minimum: 5 }
  #validates :text,  length: 
=begin  
  after_create :reindex!
  after_update :reindex!  
    
  searchable do
    text :caption, :text
    integer :id
  end
=end  
  
  def destroy
    self.cover=nil
    self.cover_id=nil
    self.save
    self.issuepages.each do |i|
       i.destroy
    end 
    super
  end
=begin  
  protected
    def reindex!
      Sunspot.index!(self)
    end
=end           
end
append_translations <<STR
ru:
  activerecord:
    models:
      issue:
        zero:   "Номеров"
        one:    "Номер"
        few:    "Номера"
        many:   "Номеров"
        other:  "Номеров"
    attributes:
      issue:
        caption:  "Заголовок"
        text:     "Содежимое"
  placeholder:
    issue:
      caption:  "Введите заголовок издания"
      text:     "Введите описание издания"
  confirm_delete:
    issue:  "Вы действительно хотите удалить номер %{title}?"
  button:
    go_issue_pages:      'Страницы'
    go_issue_page_add:   'Добавить страницу'
    go_issue_list:       'К списку номеров'
    go_issue:            'К номеру'
STR

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  layout "issue"
  model         Issue
  index_fields   :id, :caption, :text, :cover_id
  permit_params  :id, :caption, :text, :cover_id
  index_includes :cover



  def main
    @item = model.last
    render "show"
  end 
 
 
end

app/views/issues/_form.html.slim
= javascript_include_tag "/plugins/tinymce/tinymce.min.js"
= javascript_include_tag "/plugins/tinymce/paper.js"
= error_messages! @item
= form_for(@item) do |f|
 = f.text_field :caption
 = f.text_area :text
 = f.submit  :save

app/views/issues/_issue.html.slim
.thumbnail style="height:200px"
 center
  - a=issue.cover
  = link_to issue do
   - unless a.nil?
    = image_tag a.image.url(:cover)  ,:class =>"img-thumbnail"
   - else
    = image_tag "/theme/nocover.png"  ,:class =>"img-thumbnail"
   .caption
    =issue.caption

app/views/issues/edit.html.slim
-content_for :breadcrumb do
  li = link_to "Архив номеров", issues_path
  li = link_to @item.caption, issue_path(@item)
  li.active Редактирование
-if user_signed_in?
 = panel_title "Редактирование номера "+@item.caption do
  = render 'form'
 = panel do
  = button_link :back, issues_adm_path
  = button_link :go_issue_pages, issue_issuepages_path(@item),3
  = button_link :go_issue_page_add, new_issue_issuepage_path(@item),1
  = button_linkConf :delete, delete_issue_path(@item) ,4, conf_delete_msg(@item,@item.caption)

app/views/issues/index.html.slim
- content_for :breadcrumb do
 li.active Архив номеров
=panel_title "Архив номеров" do
 == will_paginate  @items
 -@items.each do |i|
  div class="col-sm-4 col-md-3"
   div.thumbnail style="height:200px"
    center
     = link_to i do
      - a=i.cover
      - unless a.nil?
       = image_tag a.image.url(:cover)  ,:class =>"img-thumbnail"
      - else
       = image_tag "/theme/nocover.png"  ,:class =>"img-thumbnail"
      div.caption
       =i.caption
 div.clearfix  
 == will_paginate  @items
 == page_entries_info @items, :model => Issue
-if user_signed_in?
 =panel do
  = button_link :create, new_issue_path
  = button_link :administrate, issues_adm_path,1

app/views/issues/index_adm.html.slim
-content_for :breadcrumb do
  li.active Архив номеров
-if user_signed_in?
 = panel_title "Архив номеров" do
  == will_paginate  @items
  - @items.each do |i|
   div class="col-sm-4 col-md-3"
    div.thumbnail style="height:220px"
     =image_link_to "/theme/pinky/edit.png",   edit_issue_path(i)
     =image_link_to "/theme/pinky/delete.png",   delete_issue_path(i), {confirm: conf_delete_msg(i,i.caption)}
     center      
      = link_to i do
       - a=i.cover;
       - unless a.nil?
        = image_tag a.image.url(:cover),:class =>"img-thumbnail"
       - else
         = image_tag "/theme/nocover.png",:class =>"img-thumbnail"
       div.caption
        =i.caption
  div.clearfix  
  == will_paginate  @items
  == page_entries_info @items, :model => Issue
 = panel do
  = button_link :create, new_issue_path

app/views/issues/new.html.slim
-content_for :breadcrumb do
  li = link_to "Архив номеров", issues_path
  li.active Создание номера
- if user_signed_in?
 =panel_title  "Создание номера" do
  = render 'form'
 = panel do
  = button_link :back, issues_adm_path

app/views/issues/show.html.erb
<%= javascript_include_tag "/plugins/turn/turn4.min.js" %>
<%= javascript_include_tag "/plugins/turn/zoom.min.js" %>
<style>
#magazine{
    
	width:100%;
}
#magazine .turn-page{
	background-color:#ccc;
	background-size:100% 100%;
}
.mag_page
{
    background-size:cover;
    background-position:center;
}
.odd
{
  background-position: left  center;
}
.even{
 background-position: right center;
}
.page
{
 background-repeat: no-repeat;
 background-size: contain;
} 

#shadow-page{
    width:600px;
    height:700px;
    position:absolute;
    top:0px;
    right:0px;
    -moz-box-shadow: 5px 5px 10px #888;
    -webkit-box-shadow: 5px 5px 10px #888;
    box-shadow: 5px 2px 10px #888;
    z-index:-1;
}
.btns{
    position: relative;
    top: -300px;
    z-index: 99999;
}
</style>
<% content_for :breadcrumb do%>
  <li><%= link_to "Архив номеров", issues_path %></li>
  <li class="active"><%=@item.caption %></li>
<%end%>

<%= panel_title @item.caption do%>

<div style="width:796px;">
<div id="magazine">
    <%if @item.issuepages.each do |page|%>
      <div style="background-image:url(<%= page.image.url(:page)%>);"></div>
    <%end.empty? then%>
     pages not yet uploaded
    <%end%>
</div>
    <div class=btns>
        <table width="100%"><tr>
          <td><a href="#" id="previous"><img src="/theme/zaya/left.png"></a></td>        
          <td align=right><a href="#" id="next" class="btn_right"><img src="/theme/zaya/right.png"></a></td>
          </tr></table></div>
</div>
<script>
   $(window).ready(function(){$('#magazine').turn(
  {display: 'double', acceleration: true,gradients: !$.isTouch,	elevation:50, autoCenter: true,
    width: 796,
    height: 587
  });});
  $(window).bind('keydown', function(e){if (e.keyCode==37)$('#magazine').turn('previous');else if (e.keyCode==39)$('#magazine').turn('next');});
  $('#next')    .click(function(e) {$('#magazine').turn('next');return false;});
  $('#previous').click(function(e) {$('#magazine').turn('previous');return false;});
</script>  
  <%= @item.text.html_safe%>
  <br>
  <%= render 'share/allsoc/like'%>
<%end%>
<%= panel do%>
  <%= button_link :back, issues_path%>
  <% if user_signed_in? %>
    <%= button_link :edit, edit_issue_path(@item) , 1%>
    <%= button_link :go_issue_pages, issue_issuepages_path(@item),3%>
    <%= button_link :go_issue_page_add, new_issue_issuepage_path(@item),1%>
    <%= button_linkConf :delete, delete_issue_path(@item) ,4, conf_delete_msg(@item,@item.caption)%>
  <%end%> 
<% end %>