config/routes.rb
Ideya::Application.routes.draw do

  root 'title#index'
  
  devise_for :users, format: false
 
  resources :papers , except: [:show,:destroy],  format: false
  #get 'papers/:id/delete'   => 'papers#destroy',    as: :delete_paper, format: false
  get 'papers/page/:page'   => 'papers#index' ,     as: :paper_page,    format: false
  get 'papers/:id'          => 'papers#show'  ,                         format: false, constraints: { id: /\d*/ }
  get 'papers/:urlname'     => 'papers#byname',     as: :paper_byname,  format: false
  get 'paper_main'          => 'papers#main'  ,     as: :paper_main,    format:false
   
  resources :news , controller: :novosts, as: :novosts, format: false  , except: [:show,:destroy]
  get 'news/admin'          => 'novosts#index_adm', as: :novosts_adm,   format: false
  get 'news/:id/delete'     => 'novosts#destroy'  , as: :delete_novost, format: false
  get 'news/:id'            => 'novosts#show'     ,                     format: false, constraints: { id: /\d*/ }
  get 'news/page/:page'     => 'novosts#index'    , as: :novosts_page,  format: false
  
  resources :articles, except: [:show,:destroy],  format: false
  get 'articles/admin'      => 'articles#index_adm',as: :articles_adm,  format: false
  get 'articles/:id/delete' => 'articles#destroy' , as: :delete_article,format: false
  get 'articles/page/:page' => 'articles#index' ,   as: :articles_page, format: false
  get 'articles/:id'        => 'articles#show'  ,                       format: false, constraints: { id: /\d*/ }

  resources :partners, format: false  , except: [:show,:destroy]
  get 'partners/:id'        => 'partners#show',                         format: false, constraints: { id: /\d*/ }
  get 'partners/:id/delete' => 'partners#destroy',  as: :delete_partner,format: false

  resources :siteimages, format: false, except: [:destroy]
   get 'siteimages/:id/delete'   => 'siteimages#destroy'    , as: :delete_siteimage,  format: false
    
  resources :issues , controller: :issues, as: :issues, format: false  , except: [:show,:destroy,:update], shallow: true do
    resources :issuepages , controller: :issuepages, path: :papers,  format: false, except: [:show,:destroy,:update,:edit]  
  end
  get 'issues/:id'            => 'issues#show'        , as: :issue,            format: false, constraints: { id: /\d*/ }
  get 'issues/page/:page'     => 'issues#index'       , as: :issues_page,      format: false
  get 'issues/:id/delete'     => 'issues#destroy'     , as: :delete_issue,     format: false
  get 'issues/admin'          => 'issues#index_adm'   , as: :issues_adm,       format: false
  get 'issuepages/:id/delete' => 'issuepages#destroy' , as: :delete_issuepage, format: false
  get 'issues/:issue_id/page/:page' => 'issuepages#index'  , as: :issuepages_page,      format: false
  get 'issues/:issue_id/cover/:id' => 'issuepages#cover'  , as: :cover_issuepage,      format: false


  get  'feedback/ads'   => 'feedback#ads'        , as: :feedback_ads        , format: false
  post 'feedback/ads'   => 'feedback#ads_post'   , as: :post_feedback_ads   , format: false
  get  'feedback/ideya' => 'feedback#ideya'      , as: :feedback_ideya      , format: false
  post 'feedback/ideya' => 'feedback#ideya_post' , as: :post_feedback_ideya , format: false

  get  'feedback/akciya1' => 'feedback#akciya1'      , as: :feedback_akciya1      , format: false
  post 'feedback/akciya1' => 'feedback#akciya1_post' , as: :post_feedback_akciya1 , format: false

  get  'vk/albums' => 'vkphotos#index' , as: :vkalbums , format: false
  get  'vk/photos/:id' => 'vkphotos#photos'  , format: false


#  get  'search/*arg' => 'search#index', as: :search ,format: false #

  get 'template/*arg' => 'template#index', as: :template, format: false

  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
    get '422', :to => 'application#server_error'
    get '500', :to => 'application#server_error'
  end

#  get 'otzivi'   => 'staticviews#ozivs'    , as: :otzivs_page, format: false

end

app/models/article.rb
# encoding: utf-8
class Article < ActiveRecord::Base
  validates :title, length: { minimum: 5 }
  validates :text,  length: { minimum: 20 }
=begin  
  after_create :reindex!
  after_update :reindex!  
    
  searchable do
    text :title, :text
    integer :id
  end
=end  
end
append_translations <<STR
ru:
  activerecord:
    models:
      article:
        zero:  "Статей"
        one:   "Статья"
        few:   "Статьи"
        many:  "Статей"
        other: "Статей"
    attributes:
      article:
        title:  "Заголовок"
        text:   "Содежимое"
        publish: "Видимость"
        layout: "Макет"
        use_template: "Использовать шаблон"
  placeholder:
      article:
        title:  "Введите заголовок статьи"
        text:   "Введите текст статьи"
        publish: "Флаг видимости статьи для посетителей"
        layout: "Введите макет (стандартный application)"
        use_template: "Использовать шаблон"
  confirm_delete:
    article: 'Вы действительно хотите удалить статью %{title}?'
STR

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  model  Article
#  layout :get_layout
  permit_params :id, :title, :text, :publish,:layout,:use_template
  
  def index
    @items = model.select(:id, :title, :text).where(:publish=>true).page(params[:page])  #params[:page]
  end


  def index_adm
    @items = model.select(:id, :title, :text).page(params[:page])  #params[:page]
  end  
  
  def show
    if @item.use_template?
     render 'show',layout: @item.layout
    else
      render 'show2',layout: @item.layout
    end
     
  end
=begin  
  private
    def get_layout
      @item.layout
    end
=end  
end

app/views/articles/_article.html.slim
=link_to article_path(article),class: "list-group-item" do
 h4.list-group-item-heading
  =article.title
 p.list-group-item-text
  == truncateB(article.text.gsub(/<.+?>/,''),:length=>500,:omission=>'')

app/views/articles/_form.html.slim
= javascript_include_tag "/plugins/tinymce/tinymce.min.js"
= javascript_include_tag "/plugins/tinymce/paper.js"
= error_messages! @item
= form_for(@item) do |f|
 = f.text_field :title
 table width="100%"
  tr
   td width="40%"
    = f.text_field :layout
   td
    = f.check_box  :use_template
   td 
    = f.check_box  :publish
 = f.text_area  :text
 = f.submit     :save

app/views/articles/edit.html.slim
- content_for :breadcrumb do
 li
  = link_to "Статьи", articles_path
 li
  = link_to @item.title, article_path(@item)
 li.active
  |
   Редактирование
- if user_signed_in?
 = panel_title "Редактирование статьи "+@item.title do
  = render 'form'
= panel do
 = button_link :back, articles_adm_path

app/views/articles/index.html.slim
- content_for :breadcrumb do
 li.active
  |
   Статьи
= panel_title "Статьи" do
 == will_paginate @items
 div.list-group
 - @items.each do |article| 
   =link_to article_path(article),class: "list-group-item" do
    h4.list-group-item-heading
     =article.title
    p.list-group-item-text
     ==truncateB(article.text.gsub(/<.+?>/,''),:length=>500,:omission=>'')
 == will_paginate @items
 == page_entries_info @items , :model => Article

app/views/articles/index_adm.html.slim
-content_for :breadcrumb do
  li.active
   |
    Статьи
-if user_signed_in?
 = panel_title "Статьи" do
  == will_paginate @items
  ul
   -@items.each do |i|
    li
     =image_link_to "/theme/pinky/edit.png",   edit_article_path(i)   
     =image_link_to "/theme/pinky/delete.png", delete_article_path(i) , {confirm: conf_delete_msg(i,i.title)}  
     =link_to i.title, article_path(i)
  == will_paginate @items
  == page_entries_info @items , :model => Article, :html => false
 = panel do
  = button_link :create, new_article_path

app/views/articles/new.html.slim
- content_for :breadcrumb do
 li
  = link_to "Статьи", articles_path
 li.active
  |
   Создание статьи
-if user_signed_in?
 = panel_title  "Создание статьи" do
  = render 'form'
= panel do
 = button_link :back, articles_adm_path

app/views/articles/show.html.slim
- content_for :breadcrumb do
 li
  = link_to "Статьи", articles_path
 li.active
  =@item.title
= panel_title @item.title do
 == @item.text
= panel do
 = button_link :back, articles_path
 -if user_signed_in?
  = button_link :edit, edit_article_path(@item) , 1

app/views/articles/show2.html.slim
- content_for :breadcrumb do
 li
  = link_to "Статьи", articles_path
 li.active
  =@item.title
== @item.text
= panel do
 = button_link :back, articles_path
 -if user_signed_in?
  = button_link :edit, edit_article_path(@item) , 1