config/routes.rb
Ideya::Application.routes.draw do

  root 'title#index'
  
  devise_for :users, format: false
 
  resources :papers , except: [:show,:destroy],  format: false
  #get 'papers/:id/delete'   => 'papers#destroy',    as: :delete_paper, format: false
  get 'papers/page/:page'   => 'papers#index' ,     as: :paper_page,    format: false
  get 'papers/:id'          => 'papers#show'  ,                         format: false, constraints: { id: /\d*/ }
  get 'papers/:urlname'     => 'papers#byname',     as: :paper_byname,  format: false
  get 'paper_main'          => 'papers#main'  ,     as: :paper_main,    format:false
   
  resources :news , controller: :novosts, as: :novosts, format: false  , except: [:show,:destroy]
  get 'news/admin'          => 'novosts#index_adm', as: :novosts_adm,   format: false
  get 'news/:id/delete'     => 'novosts#destroy'  , as: :delete_novost, format: false
  get 'news/:id'            => 'novosts#show'     ,                     format: false, constraints: { id: /\d*/ }
  get 'news/page/:page'     => 'novosts#index'    , as: :novosts_page,  format: false
  
  resources :articles, except: [:show,:destroy],  format: false
  get 'articles/admin'      => 'articles#index_adm',as: :articles_adm,  format: false
  get 'articles/:id/delete' => 'articles#destroy' , as: :delete_article,format: false
  get 'articles/page/:page' => 'articles#index' ,   as: :articles_page, format: false
  get 'articles/:id'        => 'articles#show'  ,                       format: false, constraints: { id: /\d*/ }

  resources :partners, format: false  , except: [:show,:destroy]
  get 'partners/:id'        => 'partners#show',                         format: false, constraints: { id: /\d*/ }
  get 'partners/:id/delete' => 'partners#destroy',  as: :delete_partner,format: false

  resources :siteimages, format: false, except: [:destroy]
   get 'siteimages/:id/delete'   => 'siteimages#destroy'    , as: :delete_siteimage,  format: false
    
  resources :issues , controller: :issues, as: :issues, format: false  , except: [:show,:destroy,:update], shallow: true do
    resources :issuepages , controller: :issuepages, path: :papers,  format: false, except: [:show,:destroy,:update,:edit]  
  end
  get 'issues/:id'            => 'issues#show'        , as: :issue,            format: false, constraints: { id: /\d*/ }
  get 'issues/page/:page'     => 'issues#index'       , as: :issues_page,      format: false
  get 'issues/:id/delete'     => 'issues#destroy'     , as: :delete_issue,     format: false
  get 'issues/admin'          => 'issues#index_adm'   , as: :issues_adm,       format: false
  get 'issuepages/:id/delete' => 'issuepages#destroy' , as: :delete_issuepage, format: false
  get 'issues/:issue_id/page/:page' => 'issuepages#index'  , as: :issuepages_page,      format: false
  get 'issues/:issue_id/cover/:id' => 'issuepages#cover'  , as: :cover_issuepage,      format: false


  get  'feedback/ads'   => 'feedback#ads'        , as: :feedback_ads        , format: false
  post 'feedback/ads'   => 'feedback#ads_post'   , as: :post_feedback_ads   , format: false
  get  'feedback/ideya' => 'feedback#ideya'      , as: :feedback_ideya      , format: false
  post 'feedback/ideya' => 'feedback#ideya_post' , as: :post_feedback_ideya , format: false

  get  'feedback/akciya1' => 'feedback#akciya1'      , as: :feedback_akciya1      , format: false
  post 'feedback/akciya1' => 'feedback#akciya1_post' , as: :post_feedback_akciya1 , format: false

  get  'vk/albums' => 'vkphotos#index' , as: :vkalbums , format: false
  get  'vk/photos/:id' => 'vkphotos#photos'  , format: false


#  get  'search/*arg' => 'search#index', as: :search ,format: false #

  get 'template/*arg' => 'template#index', as: :template, format: false

  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
    get '422', :to => 'application#server_error'
    get '500', :to => 'application#server_error'
  end

#  get 'otzivi'   => 'staticviews#ozivs'    , as: :otzivs_page, format: false

end

app/models/issuepage.rb
# encoding: utf-8
class Issuepage < ActiveRecord::Base
  belongs_to :issue

   has_attached_file :image,
                     :styles =>
                     {
                       :thumb => ["64x81>"  , :jpg],
                       :cover => ["110x140>", :jpg],
                       :page  => ["500x636>", :jpg]
                     },
                     :default_url   => '/theme/nocver.png',
                     :default_style => :thumb
   validates_attachment :image,
                        :present => true,
                        :content_type =>
                        {
                           :content_type => ["image/jpg","image/jpeg" ,"image/gif", "image/png"]
                        }  
                        
   validates            :image, :attachment_presence => true
                         
                        
#  scope :byissue , -> (issue) { where(:issue_id => issue.id ).order("created_at DESC") }
  
 # :last5, -> {select(:id, :title, :text,:created_at).where(:publish=>true).order("created_at DESC").limit(5)}
  
#  scope :created_before, ->(time) { where("created_at < ?", time) }
end
append_translations <<STR
ru:
  activerecord:
    models:
      issuepage:
        zero:  "Страниц"
        one:   "Страница"
        few:   "Страницы"
        many:  "Страниц"
        other: "Страниц"
    attributes:
      issuepage:
        note:    "Описание"
        image:  "Обложка"
  placeholder:
      issuepage:
        note:   "Введите описание страницы"
        image:  "Выберите файл изображения"
  confirm_delete:
    issuepage: 'Вы действительно хотите удалить страницу %{title}?'
STR

app/controllers/issuepages_controller.rb
class IssuepagesController < ApplicationController
  
  before_action :set_Issue, only: [:index, :create, :new]
  
  def index
    @items=@issue.issuepages.page(params[:page])
  end
  def new
    @item = @issue.issuepages.new
  end
 
  def create
    if user_signed_in?
      @item = @issue.issuepages.new(params.require(:issuepage).permit(:image,:note))
      if @item.save
        redirect_to @issue, notice: 'Item was successfully created.' 
      else
        render action: 'new'
      end        
    else
      notauthorized
    end
  end
  
  def destroy
    if user_signed_in?
      @issuepage = Issuepage.find(params[:id])
      @issue = @issuepage.issue
      if @issue.cover_id == @issuepage.id
        @issue.cover=nil
        @issue.save
      end
      @issuepage.destroy
      index
      render :index
    else
      notauthorized
    end    
  end
  
  def cover
    if user_signed_in?
      @issuepage = Issuepage.find(params[:id])
      @issue = @issuepage.issue
      @issue.cover = @issuepage
      @issue.save
      index
      render :index
    else
      notauthorized
    end    
  end
  
  private
    def set_Issue
      @issue = Issue.find(params[:issue_id])
    end
    def notauthorized
      render :text => '401 Unauthorized', :status => :unauthorized
    end
end

app/views/issuepages/_form.html.slim
= form_for(@issuepage) do |f|
 -if @issuepage.errors.any?
  #error_explanation
   h2 = pluralize(@issuepage.errors.count, "error") | prohibited this issuepage from being saved:
   ul
    - @issuepage.errors.full_messages.each do |msg|
     li = msg
  .actions
    = f.submit :save

app/views/issuepages/edit.html.slim
- content_for :breadcrumb do
  li = link_to "Архив номеров", issues_path
  li = link_to @issue.caption, issue_path(@issue)
  li.active Редактирование страницы

= render 'form'

= panel do
 = button_link :back, issue_issuepages_path(@issue)

app/views/issuepages/index.html.slim
- content_for :breadcrumb do
 li = link_to "Архив номеров", issues_path
 li = link_to @issue.caption, issue_path(@issue)
 li.active Страницы
= panel_title "Страницы номера "+@issue.caption do
 == will_paginate  @items
 -@items.each do |i|
  div class="col-sm-4 col-md-3"
   .thumbnail style="height:210px"
    = image_link_to "/theme/pinky/page_bookmark.gif",   cover_issuepage_path(@issue,i)             
    = image_link_to "/theme/pinky/delete.png",   delete_issuepage_path(i) , {confirm: conf_delete_msg(i,i.note)}
    center             
     = image_tag i.image.url(:cover)  ,:class =>"img-thumbnail"
     .caption = i.note
 .clearfix  
 == will_paginate  @items
 == page_entries_info @items, :model => Issuepage
- if user_signed_in?
 = panel do
  = button_link :go_issue_list, issues_adm_path
  = button_link :go_issue,      edit_issue_path(@issue),2
  = button_link :go_issue_page_add, new_issue_issuepage_path(@issue),1

app/views/issuepages/new.html.slim
- content_for :breadcrumb do
  li = link_to "Архив номеров", issues_path
  li = link_to @issue.caption, issue_path(@issue)
  li.active Добавление страницы

- if user_signed_in?
 = error_messages! @item
 = panel_title  "Добавление страницы" do
  = form_for([@issue,@item],  :html => { :multipart => true } ) do |f|  
   = f.text_field :note
   = f.file_field :image
   = f.submit  :save
 = panel do
  = button_link :back, issue_issuepages_path(@issue)